name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧹 Chores'
    labels: 
      - 'chore'
      - 'docs'
template: |
  ## Changes
  
  $CHANGES
  
  **Full Changelog**: $PREVIOUS_TAG...$RESOLVED_VERSION
